name: enterprise
description: "Enterprise App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  api_auth:
    path: packages/api_auth
  ferry: ^0.16.1+2
  ferry_hive_ce_store: ^0.0.2-dev.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  gql_exec: ^1.1.1-alpha+1699813812660
  gql_http_link: ^1.2.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  riverpod_annotation: ^3.0.3
  talker_flutter: ^5.1.5
  talker_riverpod_logger: ^5.1.5

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.10.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
