name: api_auth
description: "API Authentication Package"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  dev: ^1.0.0
  ferry: ^0.16.1+2
  gql_code_builder_serializers: ^0.1.0+1
  gql_http_link: ^1.2.0

dev_dependencies:
  build_runner: ^2.5.4
  ferry_generator: ^0.12.1-dev.2
  very_good_analysis: ^10.0.0
